openapi: 3.0.0
info:
  title: Adoption Request API
  version: "1.0"
paths:
  /adoption-requests:
    post:
      summary: Create an adoption request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - petId
              properties:
                userId:
                  type: string
                petId:
                  type: string
                message:
                  type: string
      responses:
        '201':
          description: Request created
        '400':
          description: Missing data
        '500':
          description: Internal server error
